apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-app.fullname" . }}-nfs-pvc
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "web-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.nfsPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.nfsPvc.storageClass | quote }}