apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: web-app
  {{- include "web-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}