apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-app.fullname" . }}-tls
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "web-app.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tls.tlsCrt is required" .Values.tls.tlsCrt | b64enc | quote
    }}
  tls.key: {{ required "tls.tlsKey is required" .Values.tls.tlsKey | b64enc | quote
    }}
type: kubernetes.io/tls