apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80  # Port of your kubernetes nodes
      targetPort: 8080 # Port your app is running on
      nodePort: 30001  # NodePort on the host
